repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile=black, --float-to-top]
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
# - repo: https://github.com/charliermarsh/ruff-pre-commit
#   rev: v0.4.10
#   hooks:
#   - id: ruff
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
  - id: nbstripout
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [--maxkb=6000]
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: [--allow-multiple-documents]
  # - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: [--fix=auto]
- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
  - id: autoflake
    args: [--remove-all-unused-imports, --recursive, --remove-unused-variables, --in-place, --exclude=__init__.py]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, "2", --preserve-quotes]
